# Generated by Django 5.1.2 on 2024-10-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'cinemas',
            },
        ),
    ]
